### ISSUE TITLE
The new version does not start, frieze on the Welcome logo

### ISSUE THREAD

**Issue by Dima353** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#70]
After recording by all the listed programs, the OS does not start loading, the "Welcome" logo is constantly lit.
I waited for about 30 minutes

Rufus 3.18-4.2-4.3-4.5
SD Card - Sandisk 128gb, Kingstone 32gb
Windows 10, Linux Mint

The previous firmware version works fine.

**Comment by dariocarbone** [comment]
same here, even with OS ...

**Comment by jafar-it** [comment]
For me, It didn't started at all.  I have RG35XX H

**Comment by dymek37** [comment]
Same thing with me, I have RG35XX H. I think the problem is due to the original software. For a few days the update disappeared from the Anbernic website. Today it reappeared. I haven't checked if it works yet.

**Comment by dariocarbone** [comment]
Just to be sure I downloaded again Stock OS yesterday, re-flashed it and still freezes... At this time, I think it's a firmware problem only, no answers from anyone here or from anbernic support.

**Comment by jafar-it** [comment]
> Just to be sure I downloaded again Stock OS yesterday, re-flashed it and still freezes... At this time, I think it's a firmware problem only, no answers from anyone here or from anbernic support.

It is not working for many people but many claim it worked for them.  I cannot understand why it is not working for everyone.  what is the difference?

**Comment by analyticalkoala** [comment]
> > Just to be sure I downloaded again Stock OS yesterday, re-flashed it and still freezes... At this time, I think it's a firmware problem only, no answers from anyone here or from anbernic support.
> 
> It is not working for many people but many claim it worked for them. I cannot understand why it is not working for everyone. what is the difference?

For me, Plus and H both okay.

Maybe incompatibility with some board revisions?

**Comment by Mikosz06** [comment]
I have exactly the same issue

**Comment by jafar-it** [comment]
> has anyone get in touch with anbernic support giving some info and asking for an update?
I did.  They replied with irrelevant detail.  I explained what I really want.  No reply so far,

**Comment by dariocarbone** [comment]
> > I did.  They replied with irrelevant detail.  I explained what I really want.  No reply so far,

Poor chinese company support, just what i feared....

**Comment by Mikosz06** [comment]
Maybe I don't understand something, but why are you writing to anbernic support about custom OS didn't working that they aren't authors of?

**Comment by dariocarbone** [comment]
This custom OS is a modded version of the original one, which is not working too. We're hoping that @cbepx-me could fix the bug 🙏 ,  but appearently it's due to an unknown hardware problem and no one seems to understand more...

**Comment by jafar-it** [comment]
> This custom OS is a modded version of the original one, which is not working too. We're hoping that @cbepx-me could fix the bug 🙏 , but appearently it's due to an unknown hardware problem and no one seems to understand more...
Cbepx can't. The issue is at boot time.  Cbepx just fixes things here and there.  I moved to kunulli.

**Comment by jafar-it** [comment]
> Maybe I don't understand something, but why are you writing to anbernic support about custom OS didn't working that they aren't authors of?

Because Custom and stock are almost same.  Just some scripts here and there.  If this issue is fixed by Stock, cbepx can launch another version of his mod with the new base image.

**Comment by jafar-it** [comment]
I received response from Anbernic.

> <html>
<body>
<div dir="ltr" style="color: rgb(34, 34, 34); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Sorry for the inconvinience.<br>​We've fixed this issue, mind trying V1.1.5 again? Here is a brand new link to V1.1.5, if the problem persists, please contact us.<br><br></div>
RG35XXH-V1.1.5-EN64GB-240723<br>
<a href="https://we.tl/t-JLcHPFzxgH" target="_blank">https://we.tl/t-JLcHPFzxgH</a>
<br>
Best regards.<br>
--



</body>
</html>

**Comment by dariocarbone** [comment]
A great news Indeed! Tomorrow i Will try to mount It, hoping to be lucky .... And if it goes well, maybe I think It would be a great service from @cbepx-me to publish and update ti his modded version, wich i'm starting to ask for since now!! 🙏 Please, answer @cbepx-me ...

**Comment by dariocarbone** [comment]
My two cents, by the way: muos Is a very promising cfw indeed, but either Stock OS and expecially this modded version are simply working beautiful, bread and butter, just out of the box... I'd be very sad  leaving them in favor of other cfw

**Comment by dariocarbone** [comment]
Downloaded and flashed this morning and still not working ... Frankly I'm starting to get upset with this people... Furthermore the img file inside the zipped folder, according to the name, seems to be exactly the previous one

**Comment by jafar-it** [comment]
> Downloaded and flashed this morning and still not working ... Frankly I'm starting to get upset with this people... Furthermore the img file inside the zipped folder, according to the name, seems to be exactly the previous one

Yes.  240712.  can you raise another concern on their portal? I will followup on mine but when many report the issue there is a change that thy will respond.

**Comment by jafar-it** [comment]
It is better we move on.  I have moved to KNULLI.  But will return to Stock mod if it starts working.

**Comment by Dima353** [comment]
> I received response from Anbernic.
> 
> > 
> 
> Sorry for the inconvinience.
> ​We've fixed this issue, mind trying V1.1.5 again? Here is a brand new link to V1.1.5, if the problem persists, please contact us.
> 
> RG35XXH-V1.1.5-EN64GB-240723
> https://we.tl/t-JLcHPFzxgH
> Best regards.
> --

does not work :(

**Comment by jafar-it** [comment]
> > I received response from Anbernic.
> > > 
> > 
> > 
> > Sorry for the inconvinience.
> > ​We've fixed this issue, mind trying V1.1.5 again? Here is a brand new link to V1.1.5, if the problem persists, please contact us.
> > ## RG35XXH-V1.1.5-EN64GB-240723
> > https://we.tl/t-JLcHPFzxgH
> > Best regards.
> 
> does not work :(

same

**Comment by jafar-it** [comment]
zero support from developers

**Comment by dariocarbone** [comment]
Managed to switch to Knulli and become really happy after that!!! Great cfw, with better portmaster support and amazing gui!! The disappointment about anbernic support regarding THEIR OWN firmware Is hard to forget, by the way...

**Comment by cbepx-me** [comment]
Based on the information I have obtained so far, this issue may be related to system compatibility. Please wait for anbernic to update and fix the system
